### ISSUE TITLE
User should be directly able to select image for avatar from the gallery

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/open-event-orga-app#1385] opened 2018-11-03 16:43 UTC
**Describe the feature you'd like**
The user should be directly able to select an image from the gallery for his avatar rather than uploading an URL for it.

**Would you like to work on the issue?**
YES

**Comment by iamareebjamal** [comment] 2018-11-03 17:37
Duplicate of #1182

**Closed by iamareebjamal** 2018-11-03 17:37 UTC

**Comment by codepoet2017390** [comment] 2018-11-03 17:42
@iamareebjamal can i work on #1182  instead

**Comment by iamareebjamal** [comment] 2018-11-03 18:05
Yes
