### ISSUE TITLE
New event creation show the error *Event name cannot be empty*

### ISSUE THREAD

**Issue by tavishjain** [fossasia/open-event-orga-app#1566] opened 2019-03-19 06:37 UTC
**Describe the bug**
When we try to create a new event, we get the error *Event name cannot be empty*

**To Reproduce**
Create a new event with all details entered. You will still see an event creation error

**Expected behavior**
Unexpected errors mustn't arise

**Logs**

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31106411/54585168-6e927d80-4a3f-11e9-9e96-bad616834bdf.gif)

**Smartphone Info:**
Device - Redmi Note 4
Android Version - Android Nougat

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Seems like an issue in the server

**Comment by ShridharGoel** [comment] 2019-03-19 06:56
Duplicate of #1514

**Comment by kk63852** [comment] 2019-03-19 16:04
this issue persists on my device too. could not create a new event because of this.

**Closed** 2019-03-20 12:30 UTC
