### ISSUE TITLE
NPE for LoginFragment - couldn't reproduce

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#1195] opened 2018-07-11 13:40 UTC
**Is it a ?**

- [x] Bug Report
 
### Bug Report    

**Actual Behaviour**

App crashed on clicking Log In button.

**Steps to reproduce it**

Unable to reproduce - very low priority IMO

**LogCat for the issue**

```
07-11 18:07:06.598 8625-8625/? E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.fossasia.openevent.app.data.a.a.d.a(java.lang.String)' on a null object reference
        at org.fossasia.openevent.app.core.auth.login.a.c(LoginFragment.java:64)
        at org.fossasia.openevent.app.core.auth.login.k.a(Unknown Source)
        at android.arch.lifecycle.LiveData.a(LiveData.java:109)
        at android.arch.lifecycle.LiveData.b(LiveData.java:121)
        at android.arch.lifecycle.LiveData.a(LiveData.java:59)
        at android.arch.lifecycle.LiveData$a.a(LiveData.java:416)
        at android.arch.lifecycle.LiveData$LifecycleBoundObserver.a(LiveData.java:368)
        at android.arch.lifecycle.i$a.a(LifecycleRegistry.java:354)
        at android.arch.lifecycle.i.a(LifecycleRegistry.java:292)
        at android.arch.lifecycle.i.d(LifecycleRegistry.java:332)
        at android.arch.lifecycle.i.b(LifecycleRegistry.java:137)
        at android.arch.lifecycle.i.a(LifecycleRegistry.java:123)
        at android.support.v4.app.i.N(Fragment.java:2377)
        at android.support.v4.app.o.a(FragmentManager.java:1460)
        at android.support.v4.app.o.f(FragmentManager.java:1752)
        at android.support.v4.app.o.a(FragmentManager.java:1821)
        at android.support.v4.app.c.b(BackStackRecord.java:855)
        at android.support.v4.app.o.b(FragmentManager.java:2592)
        at android.support.v4.app.o.a(FragmentManager.java:2382)
        at android.support.v4.app.o.b(FragmentManager.java:2337)
        at android.support.v4.app.o.a(FragmentManager.java:853)
        at android.support.v4.app.o.c(FragmentManager.java:796)
        at android.support.v4.app.j.onBackPressed(FragmentActivity.java:186)
        at android.app.Activity.onKeyUp(Activity.java:2494)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2667)
        at android.app.Activity.dispatchKeyEvent(Activity.java:2751)
        at android.support.v7.app.e.dispatchKeyEvent(AppCompatActivity.java:534)
        at android.support.v7.view.i.dispatchKeyEvent(WindowCallbackWrapper.java:58)
        at android.support.v7.app.h$b.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
        at android.support.v7.view.i.dispatchKeyEvent(WindowCallbackWrapper.java:58)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4164)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4126)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3819)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3701)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3876)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3701)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3852)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4018)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2290)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1911)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1902)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2267)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
    	at android.os.MessageQueue.next(MessageQueue
07-11 18:07:06.731 11977-12072/? E/fb4a.BackgroundLocationReportingManager: Starting location collection failed due to PERMISSION_DENIED, will retry when location services returns
07-11 18:07:06.732 8625-8625/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.organizer, PID: 8625
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.fossasia.openevent.app.data.a.a.d.a(java.lang.String)' on a null object reference
        at org.fossasia.openevent.app.core.auth.login.a.c(LoginFragment.java:64)
        at org.fossasia.openevent.app.core.auth.login.k.a(Unknown Source)
        at android.arch.lifecycle.LiveData.a(LiveData.java:109)
        at android.arch.lifecycle.LiveData.b(LiveData.java:121)
        at android.arch.lifecycle.LiveData.a(LiveData.java:59)
        at android.arch.lifecycle.LiveData$a.a(LiveData.java:416)
        at android.arch.lifecycle.LiveData$LifecycleBoundObserver.a(LiveData.java:368)
        at android.arch.lifecycle.i$a.a(LifecycleRegistry.java:354)
        at android.arch.lifecycle.i.a(LifecycleRegistry.java:292)
        at android.arch.lifecycle.i.d(LifecycleRegistry.java:332)
        at android.arch.lifecycle.i.b(LifecycleRegistry.java:137)
        at android.arch.lifecycle.i.a(LifecycleRegistry.java:123)
        at android.support.v4.app.i.N(Fragment.java:2377)
        at android.support.v4.app.o.a(FragmentManager.java:1460)
        at android.support.v4.app.o.f(FragmentManager.java:1752)
        at android.support.v4.app.o.a(FragmentManager.java:1821)
        at android.support.v4.app.c.b(BackStackRecord.java:855)
        at android.support.v4.app.o.b(FragmentManager.java:2592)
        at android.support.v4.app.o.a(FragmentManager.java:2382)
        at android.support.v4.app.o.b(FragmentManager.java:2337)
        at android.support.v4.app.o.a(FragmentManager.java:853)
        at android.support.v4.app.o.c(FragmentManager.java:796)
        at android.support.v4.app.j.onBackPressed(FragmentActivity.java:186)
        at android.app.Activity.onKeyUp(Activity.java:2494)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2667)
        at android.app.Activity.dispatchKeyEvent(Activity.java:2751)
        at android.support.v7.app.e.dispatchKeyEvent(AppCompatActivity.java:534)
        at android.support.v7.view.i.dispatchKeyEvent(WindowCallbackWrapper.java:58)
        at android.support.v7.app.h$b.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
        at android.support.v7.view.i.dispatchKeyEvent(WindowCallbackWrapper.java:58)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4164)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4126)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3819)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3701)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3876)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3701)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3852)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4018)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2290)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1911)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1902)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2267)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
    	at android.os.MessageQueue.nativePollOn
```

**Android version and Phone Model**
6.0.1 MMB29M - Redmi 4A

**Comment by Masquerade0097** [comment] 2018-07-22 17:38
I'm unable to reproduce it either. @sridharjajoo Please verify it.

**Comment by sridharjajoo** [comment] 2018-07-22 17:39
Even I am not able to reproduce the error. You can close this issue

**Closed** 2018-07-22 17:39 UTC
