### ISSUE TITLE
Create new Event button open Activity 2 times

### ISSUE THREAD

**Issue by ankush-01** [fossasia/open-event-orga-app#1401] opened 2018-12-01 09:14 UTC
Current Behaviour : 
    if user create create new event activity , it opens activity two time..
Expected Behaviour :
    activity should be open only 1 time.

![videotogif_2018 12 01_14 43 13](https://user-images.githubusercontent.com/33266550/49326390-94227680-f577-11e8-837e-2456db21dc45.gif)

**Comment by vanshikaarora** [comment] 2019-01-06 17:37
Hey which device are you using i am not able to produce the issue

**Comment by angmas1** [comment] 2019-01-15 07:32
That happens when you click the fab twice before the activity opens.

**Comment by ShridharGoel** [comment] 2019-01-15 07:48
@angmas1 Still not able to reproduce the issue. Can you create a GIF and share it?

**Comment by ShridharGoel** [comment] 2019-01-15 07:50
@angmas1 Still not able to reproduce the issue. Have you pulled the latest commits on the development branch?

**Comment by vanshikaarora** [comment] 2019-01-15 09:02
Yes it would be great if you can share a gif here @angmas1

**Comment by angmas1** [comment] 2019-02-01 06:33
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/37517284/52106577-5692a600-2619-11e9-9057-eb8f6c2b4662.gif)

Just press the fab rapidly.

**Comment by iamareebjamal** [comment] 2019-02-01 16:47
Did you press the FAB twice quickly?

**Comment by iamareebjamal** [comment] 2019-02-01 16:48
> That happens when you click the fab twice before the activity opens.

Closing. If you shoot your foot twice, don't expect to find one hole. If you'll click twice, it'll open twice

**Closed by iamareebjamal** 2019-02-01 16:48 UTC
