### ISSUE TITLE
App crashes on opening event 

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-orga-app#1671] opened 2019-05-27 07:35 UTC
**Describe the bug**
App crashes on opening event 

**Logs**
```
W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
        at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onError(CompletableAndThenCompletable.java:104)
W/System.err:     at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
        at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:38)
        at io.reactivex.Completable.subscribe(Completable.java:2302)
        at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.Completable.subscribe(Completable.java:2302)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onComplete(SingleFlatMapCompletable.java:102)
        at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:43)
        at io.reactivex.Completable.subscribe(Completable.java:2302)
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
        at io.reactivex.internal.operators.observable.ObservableToListSingle$ToListObserver.onComplete(ObservableToListSingle.java:111)
        at io.reactivex.internal.observers.BasicFuseableObserver.onComplete(BasicFuseableObserver.java:119)
        at io.reactivex.internal.operators.observable.ObservableFromIterable$FromIterableDisposable.run(ObservableFromIterable.java:113)
        at io.reactivex.internal.operators.observable.ObservableFromIterable.subscribeActual(ObservableFromIterable.java:58)
W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58)
        at io.reactivex.Single.subscribe(Single.java:3575)
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable.subscribeActual(SingleFlatMapCompletable.java:44)
        at io.reactivex.Completable.subscribe(Completable.java:2302)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable.subscribeActual(CompletableAndThenCompletable.java:35)
        at io.reactivex.Completable.subscribe(Completable.java:2302)
        at io.reactivex.Completable.subscribe(Completable.java:2288)
        at com.eventyay.organizer.data.attendee.AttendeeRepositoryImpl.lambda$null$2$AttendeeRepositoryImpl(AttendeeRepositoryImpl.java:65)
        at com.eventyay.organizer.data.attendee.-$$Lambda$AttendeeRepositoryImpl$wGSt4RrT4NMcKL0J0t8Ij5SNFR0.accept(lambda)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:93)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:51)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:43)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableFlattenIterable.subscribeActual(ObservableFlattenIterable.java:44)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:40)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableSwitchIfEmpty$SwitchIfEmptyObserver.onComplete(ObservableSwitchIfEmpty.java:70)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onComplete(ObservableDoOnEach.java:141)
        at io.reactivex.internal.operators.single.SingleFlatMapIterableObservable$FlatMapIterableObserver.onSuccess(SingleFlatMapIterableObservable.java:99)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:56)
        at io.reactivex.Single.subscribe(Single.java:3575)
        at io.reactivex.internal.operators.single.SingleFlatMapIterableObservable.subscribeActual(SingleFlatMapIterableObservable.java:47)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:40)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:40)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableSwitchIfEmpty.subscribeActual(ObservableSwitchIfEmpty.java:31)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58)
        at io.reactivex.Single.subscribe(Single.java:3575)
        at io.reactivex.internal.operators.single.SingleFlatMapIterableObservable.subscribeActual(SingleFlatMapIterableObservable.java:47)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
W/System.err:     at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
W/System.err:     at com.raizlabs.android.dbflow.structure.database.AndroidDatabaseStatement.executeInsert(AndroidDatabaseStatement.java:83)
        at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.insert(ModelSaver.java:114)
        at com.raizlabs.android.dbflow.sql.saveable.ListModelSaver.insertAll(ListModelSaver.java:55)
        at com.raizlabs.android.dbflow.structure.ModelAdapter.insertAll(ModelAdapter.java:220)
W/System.err:     at com.raizlabs.android.dbflow.structure.database.transaction.FastStoreModelTransaction$2.processModel(FastStoreModelTransaction.java:36)
        at com.raizlabs.android.dbflow.structure.database.transaction.FastStoreModelTransaction.execute(FastStoreModelTransaction.java:88)
        at com.raizlabs.android.dbflow.config.DatabaseDefinition.executeTransaction(DatabaseDefinition.java:283)
W/System.err:     at com.eventyay.organizer.data.db.DbFlowDatabaseRepository.lambda$saveList$4(DbFlowDatabaseRepository.java:62)
W/System.err:     at com.eventyay.organizer.data.db.-$$Lambda$DbFlowDatabaseRepository$vQ9a4igUC0l5e_a97-Xc5KUy-7c.run(lambda)
        at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:34)
    	... 68 more
E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
    Process: com.eventyay.organizer, PID: 8825
    io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
        at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onError(CompletableAndThenCompletable.java:104)
        at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
        at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:38)
        at io.reactivex.Completable.subscribe(Completable.java:2302)
        at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.Completable.subscribe(Completable.java:2302)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onComplete(SingleFlatMapCompletable.java:102)
        at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:43)
        at io.reactivex.Completable.subscribe(Completable.java:2302)
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
        at io.reactivex.internal.operators.observable.ObservableToListSingle$ToListObserver.onComplete(ObservableToListSingle.java:111)
        at io.reactivex.internal.observers.BasicFuseableObserver.onComplete(BasicFuseableObserver.java:119)
        at io.reactivex.internal.operators.observable.ObservableFromIterable$FromIterableDisposable.run(ObservableFromIterable.java:113)
        at io.reactivex.internal.operators.observable.ObservableFromIterable.subscribeActual(ObservableFromIterable.java:58)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58)
        at io.reactivex.Single.subscribe(Single.java:3575)
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable.subscribeActual(SingleFlatMapCompletable.java:44)
        at io.reactivex.Completable.subscribe(Completable.java:2302)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable.subscribeActual(CompletableAndThenCompletable.java:35)
        at io.reactivex.Completable.subscribe(Completable.java:2302)
        at io.reactivex.Completable.subscribe(Completable.java:2288)
        at com.eventyay.organizer.data.attendee.AttendeeRepositoryImpl.lambda$null$2$AttendeeRepositoryImpl(AttendeeRepositoryImpl.java:65)
        at com.eventyay.organizer.data.attendee.-$$Lambda$AttendeeRepositoryImpl$wGSt4RrT4NMcKL0J0t8Ij5SNFR0.accept(lambda)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:93)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:51)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:43)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
    	at io
```

**Would you like to work on the issue?**
Open to all

**Comment by ShridharGoel** [comment] 2019-05-27 07:53
@anhanh11001 When exactly is the app crashing? Not able to reproduce. Can you please add a GIF?

**Comment by anhanh11001** [comment] 2019-05-27 08:01
<img src="https://i.ibb.co/qrZLkSp/ezgif-2-43575805e037.gif" alt="ezgif-2-43575805e037" border="0">

I use the release app but it is also reproducible in debug app

**Comment by anhanh11001** [comment] 2019-06-04 09:41
@ShridharGoel I tested again today and this is not reproducible in the latest updates. I'm not sure if it is really fixed

**Comment by ShridharGoel** [comment] 2019-06-04 09:55
@anhanh11001 I'm also not able to reproduce this. So should we close this?

**Closed** 2019-06-04 10:47 UTC
